spring:
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: false
  datasource:
    username: root
    password: 123123123
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
